//  _____ _
// |_   _| |_  _ _ ___ ___ _ __  __ _
//   | | | ' \| '_/ -_) -_) '  \/ _` |_
//   |_| |_||_|_| \___\___|_|_|_\__,_(_)
//
// Threema iOS Client
// Copyright (c) 2017-2021 Threema GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License, version 3,
// as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#import <ThreemaFramework/Colors.h>
#import "TextStyleUtils.h"
#import "Constants.h"
#import "LogLevelCustom.h"
#import "PlayRecordAudioViewController.h"
#import "SendLocationAction.h"
#import "MWPhotoBrowser.h"
#import "MWPhoto.h"
#import "UserSettings.h"
#import "ValidationLogger.h"
#import "Colors.h"
#import "MyIdentityStore.h"
#import "Utils.h"
#import "BundleUtil.h"
#import "ThemedTableViewController.h"
#import "LicenseStore.h"
#import "CryptoUtils.h"
#import "FullscreenImageViewController.h"
#import "ModalNavigationController.h"
#import "AbstractMessage.h"
#import "ContactStore.h"
#import "LicenseStore.h"
#import "AppGroup.h"
#import "Conversation.h"
#import "AvatarMaker.h"
#import "EntityManager.h"
#import "NSString+Hex.h"
#import "QuoteParser.h"
#import "BaseMessage.h"
#import "TextMessage.h"
#import "ImageMessage.h"
#import "VideoMessage.h"
#import "SystemMessage.h"
#import "MessageFetcher.h"
#import "GroupProxy.h"
#import "DatabaseManager.h"
#import "MessageSender.h"
#import "MediaConverter.h"
#import "PortraitNavigationController.h"
#import "QRCodeViewController.h"
#import "MDMSetup.h"
#import "Constants.h"
#import "ProtocolDefines.h"
#import "NaClCrypto.h"
#import "GroupPhotoSender.h"
#import "BlobMessageLoader.h"
#import "VideoMessageLoader.h"
#import "ImageMessageLoader.h"
#import "ChatViewControllerCache.h"
#import "MessageDraftStore.h"
#import "FileMessageSender.h"
#import "FeatureMask.h"
#import "DocumentManager.h"
#import "PushSetting.h"
#import "NotificationManager.h"
#import "ErrorHandler.h"
#import "ScanIdentityController.h"
#import "UIDefines.h"
#import "ServerConnector.h"
#import "MessageQueue.h"
#import "OrderedDictionary.h"
#import "PermissionChecker.h"
#import "PushPayloadDecryptor.h"
#import "MessageSender.h"
#import <CommonCrypto/CommonHMAC.h>
#import "saltyrtc_task_relayed_data_ffi.h"
#import <WebRTC/WebRTC.h>
#import "Scrypt.h"
#import "IDCreationPageViewController.h"
#import "RestoreIdentityViewController.h"
#import "ServerAPIConnector.h"
#import "IntroQuestionView.h"
#import "RectUtil.h"
#import "PhoneNumberNormalizer.h"
#import "UIImage+ColoredImage.h"
#import "UIDefines.h"
#import "BrandingUtils.h"
#import "KKPasscodeSettingsViewController.h"
#import "InviteController.h"
#import "AddThreemaChannelController.h"
#import "NibUtil.h"
#import "StatusNavigationBar.h"
#import "EditContactViewController.h"
#import "BoxVoIPCallOfferMessage.h"
#import "BoxVoIPCallAnswerMessage.h"
#import "BoxVoIPCallIceCandidatesMessage.h"
#import "BoxVoIPCallHangupMessage.h"
#import "BoxVoIPCallRingingMessage.h"
#import "VoIPHelper.h"
#import <MediaPlayer/MediaPlayer.h>
#import "ContactPhotoSender.h"
#import "ContactGroupMembershipViewController.h"
#import "ChatBlobMessageCell.h"
#import "ChatDefines.h"
#import "BoxFileMessage.h"
#import "GroupFileMessage.h"
#import "NSString+Emoji.h"
#import "ZSWTappableLabel.h"
#import "ChatTextMessageCell.h"
#import "UILabel+Markup.h"
#import "ActivityUtil.h"
#import "MessageActivityItem.h"
#import "ChatViewController.h"
#import "UTIConverter.h"
#import "URLHandler.h"
#import "PushSoundViewController.h"
#import "FLAnimatedImageView.h"
#import "FLAnimatedImage.h"
#import "AnimGifMessageLoader.h"
#import "Reachability.h"
#import "NonFirstResponderActionSheet.h"
#import "CreatePasswordTrigger.h"
#import "SendMediaAction.h"
#import "CreatePasswordTrigger.h"
#import "HairlineView.h"
