#ifndef Threema_FileMessageKeys_h
#define Threema_FileMessageKeys_h

#define JSON_FILE_KEY_FILE_BLOB @"b"
#define JSON_FILE_KEY_THUMBNAIL_BLOB @"t"
#define JSON_FILE_KEY_ENCRYPTION_KEY @"k"
#define JSON_FILE_KEY_MIMETYPE @"m"
#define JSON_FILE_KEY_MIMETYPETHUMBNAIL @"p"
#define JSON_FILE_KEY_FILENAME @"n"
#define JSON_FILE_KEY_FILESIZE @"s"
#define JSON_FILE_KEY_TYPE_DEPRECATED @"i"
#define JSON_FILE_KEY_TYPE @"j"
#define JSON_FILE_KEY_DESCRIPTION @"d"
#define JSON_FILE_KEY_CORRELATION @"c"

#define JSON_FILE_KEY_METADATA @"x"
#define JSON_FILE_KEY_METADATA_HEIGHT @"h"
#define JSON_FILE_KEY_METADATA_WIDTH @"w"
#define JSON_FILE_KEY_METADATA_DURATION @"d"

#endif
